import type { LocalActivity } from './activity';

const DB_NAME = 'flinkout'; const STORE = 'activities';
function normalise(activity: LocalActivity): LocalActivity { const gpsDistanceM = activity.gpsDistanceM ?? activity.distanceM; return { ...activity, published: activity.published ?? activity.syncStatus === 'SYNCED', syncStatus: activity.syncStatus ?? 'LOCAL', syncError: activity.syncError ?? null, syncedActivityId: activity.syncedActivityId ?? null, lastSyncAttemptAt: activity.lastSyncAttemptAt ?? null, gpsDistanceM, sensorDistanceM: activity.sensorDistanceM ?? 0, sensorDistanceOffsetM: activity.sensorDistanceOffsetM ?? activity.distanceM, steps: activity.steps ?? 0, distanceSource: activity.distanceSource ?? (activity.route.length ? 'GPS' : 'NONE'), lastSensorAt: activity.lastSensorAt ?? null, liveRequested: activity.liveRequested ?? false, liveSessionId: activity.liveSessionId ?? null, liveEndStatus: activity.liveEndStatus ?? null, timeline: activity.timeline ?? [] }; }
function db() { return new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => { const store = request.result.createObjectStore(STORE, { keyPath: 'clientId' }); store.createIndex('status', 'status'); store.createIndex('updatedAt', 'updatedAt'); }; request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
export async function putActivity(activity: LocalActivity) { const database = await db(); return new Promise<void>((resolve, reject) => { const tx = database.transaction(STORE, 'readwrite'); tx.objectStore(STORE).put(activity); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); }
export async function getIncompleteActivity() { const database = await db(); return new Promise<LocalActivity | undefined>((resolve, reject) => { const request = database.transaction(STORE).objectStore(STORE).getAll(); request.onsuccess = () => resolve((request.result as LocalActivity[]).map(normalise).filter(activity => activity.status !== 'FINISHED' || !activity.published).sort((a, b) => Date.parse(b.updatedAt) - Date.parse(a.updatedAt))[0]); request.onerror = () => reject(request.error); }); }
export async function getActivity(id: string) { const database = await db(); return new Promise<LocalActivity | undefined>((resolve, reject) => { const request = database.transaction(STORE).objectStore(STORE).get(id); request.onsuccess = () => resolve(request.result ? normalise(request.result) : undefined); request.onerror = () => reject(request.error); }); }
export async function getActivitiesReadyForSync() { const database = await db(); return new Promise<LocalActivity[]>((resolve, reject) => { const request = database.transaction(STORE).objectStore(STORE).getAll(); request.onsuccess = () => resolve((request.result as LocalActivity[]).map(normalise).filter(activity => activity.status === 'FINISHED' && activity.published && activity.syncStatus !== 'SYNCED' && activity.syncStatus !== 'SYNCING').sort((a, b) => Date.parse(a.updatedAt) - Date.parse(b.updatedAt))); request.onerror = () => reject(request.error); }); }
export async function deleteActivity(id: string) { const database = await db(); return new Promise<void>((resolve, reject) => { const tx = database.transaction(STORE, 'readwrite'); tx.objectStore(STORE).delete(id); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); }
