import { Router } from 'express';
import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { ApiError } from '../lib/http.js';
import { prisma } from '../lib/prisma.js';
import { authenticate } from '../middleware/auth.js';
import { distanceKm } from './discovery.js';

export const liveRouter = Router();
const updateSchema = z.object({ type: z.enum(['WALK','RUN','RIDE','HIKE']).optional(), visibility: z.enum(['PUBLIC','FOLLOWERS','PRIVATE']).optional(), latitude: z.number().gte(-90).lte(90), longitude: z.number().gte(-180).lte(180), durationS: z.number().int().min(0).max(86_400), distanceM: z.number().min(0).max(2_000_000) });
const nearbySchema = z.object({ latitude: z.coerce.number().gte(-90).lte(90), longitude: z.coerce.number().gte(-180).lte(180), radiusKm: z.coerce.number().min(1).max(50).default(10) });
const approximate = (value: number) => Math.round(value * 100) / 100;
function range(lat: number, lng: number, km: number) { const dLat = km / 111; const dLng = km / (111 * Math.max(Math.cos(lat * Math.PI / 180), .1)); return { dLat, dLng }; }
async function visible(session: { userId: string; visibility: string }, viewerId: string) { return session.userId === viewerId || session.visibility === 'PUBLIC' || (session.visibility === 'FOLLOWERS' && Boolean(await prisma.follow.findUnique({ where: { followerId_followingId: { followerId: viewerId, followingId: session.userId } } }))); }

liveRouter.post('/start', authenticate, async (req, res, next) => { try { const data = updateSchema.extend({ type: z.enum(['WALK','RUN','RIDE','HIKE']), visibility: z.enum(['PUBLIC','FOLLOWERS','PRIVATE']).default('FOLLOWERS') }).parse(req.body); await prisma.liveActivity.updateMany({ where: { userId: req.currentUser!.id, active: true }, data: { active: false, endedAt: new Date() } }); const live = await prisma.liveActivity.create({ data: { userId: req.currentUser!.id, type: data.type, visibility: data.visibility, latitude: approximate(data.latitude), longitude: approximate(data.longitude), durationS: data.durationS, distanceM: Math.round(data.distanceM) } }); res.status(201).json({ live }); } catch (error) { next(error); } });
liveRouter.put('/current', authenticate, async (req, res, next) => { try { const data = updateSchema.parse(req.body); const live = await prisma.liveActivity.findFirst({ where: { userId: req.currentUser!.id, active: true }, orderBy: { startedAt: 'desc' } }); if (!live) throw new ApiError(404, 'No active live activity'); const updated = await prisma.liveActivity.update({ where: { id: live.id }, data: { ...(data.type ? { type: data.type } : {}), ...(data.visibility ? { visibility: data.visibility } : {}), latitude: approximate(data.latitude), longitude: approximate(data.longitude), durationS: data.durationS, distanceM: Math.round(data.distanceM) } }); res.json({ live: updated }); } catch (error) { next(error); } });
liveRouter.delete('/current', authenticate, async (req, res, next) => { try { await prisma.liveActivity.updateMany({ where: { userId: req.currentUser!.id, active: true }, data: { active: false, endedAt: new Date() } }); res.status(204).send(); } catch (error) { next(error); } });
liveRouter.get('/nearby', authenticate, async (req, res, next) => { try { const q = nearbySchema.parse(req.query); const b = range(q.latitude, q.longitude, q.radiusKm); const freshSince = new Date(Date.now() - 120_000); const sessions = await prisma.liveActivity.findMany({ where: { active: true, lastUpdatedAt: { gte: freshSince }, latitude: { gte: q.latitude - b.dLat, lte: q.latitude + b.dLat }, longitude: { gte: q.longitude - b.dLng, lte: q.longitude + b.dLng }, OR: [{ userId: req.currentUser!.id }, { visibility: 'PUBLIC' }, { visibility: 'FOLLOWERS', user: { followers: { some: { followerId: req.currentUser!.id } } } }] }, include: { user: { select: { id: true, username: true, profile: { select: { displayName: true, photoUrl: true } } } }, _count: { select: { joins: true } } }, take: 30, orderBy: { lastUpdatedAt: 'desc' } }); const live = sessions.map(session => ({ id: session.id, type: session.type, visibility: session.visibility, latitude: session.latitude, longitude: session.longitude, durationS: session.durationS, distanceM: session.distanceM, startedAt: session.startedAt, joinCount: session._count.joins, distanceKm: distanceKm(q.latitude, q.longitude, session.latitude, session.longitude), user: { id: session.user.id, username: session.user.username, displayName: session.user.profile?.displayName ?? session.user.username, photoUrl: session.user.profile?.photoUrl ?? null } })).filter(session => session.distanceKm <= q.radiusKm); res.json({ live }); } catch (error) { next(error); } });
liveRouter.post('/:id/join', authenticate, async (req, res, next) => { try { const id = z.string().cuid().parse(req.params.id); const session = await prisma.liveActivity.findUnique({ where: { id } }); if (!session || !session.active) throw new ApiError(404, 'Live activity not found'); if (session.userId === req.currentUser!.id) throw new ApiError(400, 'You cannot join your own live activity'); if (!await visible(session, req.currentUser!.id)) throw new ApiError(403, 'You cannot join this live activity'); await prisma.liveActivityJoin.upsert({ where: { liveActivityId_userId: { liveActivityId: id, userId: req.currentUser!.id } }, update: {}, create: { liveActivityId: id, userId: req.currentUser!.id } }); res.status(201).json({ joined: true }); } catch (error) { next(error); } });
liveRouter.delete('/:id/join', authenticate, async (req, res, next) => { try { const id = z.string().cuid().parse(req.params.id); await prisma.liveActivityJoin.deleteMany({ where: { liveActivityId: id, userId: req.currentUser!.id } }); res.status(204).send(); } catch (error) { next(error); } });
