import express from 'express';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import { env } from './config/env.js';
import { errorHandler, notFound } from './lib/http.js';
import { authRouter } from './routes/auth.js';
import { usersRouter } from './routes/users.js';
import { activitiesRouter } from './routes/activities.js';
import { discoveryRouter } from './routes/discovery.js';
import { liveRouter } from './routes/live.js';
import { heatmapRouter } from './routes/heatmap.js';
import { requireTrustedOrigin } from './middleware/origin.js';
import { rateLimit } from './middleware/rate-limit.js';

export const app = express();
app.use(helmet());
app.use(cors({ origin: env.WEB_ORIGIN, credentials: true }));
app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use(express.json({ limit: '5mb' }));
app.use(cookieParser());
app.use(requireTrustedOrigin);
app.use('/api/v1', rateLimit());
app.use('/api/v1/auth/login', rateLimit(10, 60_000));
app.use('/api/v1/auth/register', rateLimit(5, 60_000));
app.get('/api/v1/health', (_req, res) => res.json({ status: 'ok' }));
app.use('/api/v1/auth', authRouter);
app.use('/api/v1/users', usersRouter);
app.use('/api/v1/activities', activitiesRouter);
app.use('/api/v1/discovery', discoveryRouter);
app.use('/api/v1/live', liveRouter);
app.use('/api/v1/heatmap', heatmapRouter);
app.use(notFound);
app.use(errorHandler);
