'use client';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { useState } from 'react';
import { api, type NearbyActivity, type NearbyPerson, type User } from '../lib/api';
import { formatDistance, labelFor } from '../lib/activity';
const NearbyMap = dynamic(() => import('./nearby-map').then(module => module.NearbyMap), { ssr: false, loading: () => <div className="map"/> });
type Result = { people: NearbyPerson[]; activities: NearbyActivity[]; precision: string };
const preview: Result = { precision: 'demo', people: [{ id:'preview-maya',username:'maya_runs',displayName:'Maya Patel',photoUrl:null,latitude:19.076,longitude:72.878,distanceKm:1.2 },{ id:'preview-arjun',username:'arjun_moves',displayName:'Arjun Mehta',photoUrl:null,latitude:19.082,longitude:72.872,distanceKm:3.1 }], activities: [{ id:'preview-activity',type:'RUN',startedAt:new Date().toISOString(),distanceM:6400,latitude:19.073,longitude:72.883,distanceKm:1.8,route:null,user:{id:'preview-maya',username:'maya_runs',displayName:'Maya Patel',photoUrl:null}}] };
export function DiscoveryExperience({ mapOnly = false }: { mapOnly?: boolean }) { const [result, setResult] = useState<Result>(preview); const [center, setCenter] = useState<[number, number]>([19.076,72.878]); const [radius, setRadius] = useState(10); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [search, setSearch] = useState(''); const [users, setUsers] = useState<User[]>([]);
  function discover() { if (!navigator.geolocation) { setError('Location is unavailable in this browser.'); return; } setLoading(true); setError(''); navigator.geolocation.getCurrentPosition(async position => { const location = { latitude: position.coords.latitude, longitude: position.coords.longitude }; try { await api('/discovery/location', { method: 'PUT', body: JSON.stringify(location) }); const nearby = await api<Result>(`/discovery/nearby?latitude=${location.latitude}&longitude=${location.longitude}&radiusKm=${radius}`); setCenter([location.latitude, location.longitude]); setResult(nearby); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load nearby discovery'); } finally { setLoading(false); } }, geolocationError => { setLoading(false); setError(geolocationError.code === geolocationError.PERMISSION_DENIED ? 'Location permission was denied. You can still search for people by name.' : 'No location is currently available. Try again outdoors or check device location settings.'); }, { enableHighAccuracy: false, timeout: 12_000, maximumAge: 300_000 }); }
  async function findPeople(event: React.FormEvent) { event.preventDefault(); if (!search.trim()) return; try { const found = await api<{users: User[]}>(`/users/search?q=${encodeURIComponent(search.trim())}`); setUsers(found.users); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not search people'); } }
  const controls = <section className="card discovery-controls"><div><h2>{mapOnly ? 'Nearby map' : 'Discover nearby'}</h2><p className="hint">Your stored discovery location is rounded to roughly 1 km.</p></div><label className="field">Radius<select value={radius} onChange={event => setRadius(Number(event.target.value))}><option value={5}>5 km</option><option value={10}>10 km</option><option value={25}>25 km</option><option value={50}>50 km</option></select></label><button className="button" disabled={loading} onClick={discover}>{loading ? 'Finding nearby…' : 'Use my location'}</button></section>;
  if (mapOnly) return <section className="stack"><div className="hero"><h1>Nearby map</h1><p>Explore public activity areas and opt-in nearby people.</p></div>{controls}{error && <p className="error" role="alert">{error}</p>}{center && result ? <><NearbyMap center={center} radiusKm={radius} people={result.people} activities={result.activities}/><p className="hint">Showing {result.people.length} people and {result.activities.length} public activities. Locations are approximate.</p></> : <section className="card empty-state"><p>Choose “Use my location” to load a privacy-safe nearby map.</p></section>}</section>;
  return <section className="stack"><div className="hero"><h1>Explore</h1><p>Find movers and public activities around you—without exposing exact locations.</p></div>{controls}{error && <p className="error" role="alert">{error}</p>}<section className="card stack"><h2>Find people</h2><form className="row" onSubmit={findPeople}><label className="sr-only" htmlFor="people-search">Search people</label><input id="people-search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search by name or username"/><button className="button secondary">Search</button></form>{users.map(user => <Link className="row search-person" key={user.id} href={`/u/${user.username}`}><span className="avatar small">{user.profile?.displayName[0] ?? user.username[0]}</span><span><strong>{user.profile?.displayName}</strong><small>@{user.username}</small></span></Link>)}</section>{result && <><section className="card stack"><h2>People Near You</h2>{result.people.length ? result.people.map(person => <Link className="row nearby-row" key={person.id} href={`/u/${person.username}`}><span className="avatar small">{person.displayName[0]}</span><span className="grow"><strong>{person.displayName}</strong><small>@{person.username}</small></span><span className="hint">~{person.distanceKm.toFixed(1)} km</span></Link>) : <p className="hint">No discoverable people nearby yet.</p>}</section><section className="card stack"><h2>Activities Near You</h2>{result.activities.length ? result.activities.map(activity => <Link className="nearby-row row" key={activity.id} href={`/activities/${activity.id}`}><span className="activity-type">{labelFor(activity.type)}</span><span className="grow"><strong>{activity.user.displayName}</strong><small>{formatDistance(activity.distanceM)} · ~{activity.distanceKm.toFixed(1)} km away</small></span></Link>) : <p className="hint">No public activity areas nearby yet.</p>}</section><section className="card stack"><h2>Activity Areas</h2>{center && <NearbyMap center={center} radiusKm={radius} people={result.people} activities={result.activities}/>}<Link className="button secondary" href="/map">Open full map</Link></section></>}</section>; }
