'use client';
import { useEffect, useState } from 'react';
import { api, type LiveActivity } from '../lib/api';
import { formatDistance, formatDuration, labelFor } from '../lib/activity';

const demo: LiveActivity[] = [
  { id: 'demo-live-1', type: 'RUN', visibility: 'PUBLIC', latitude: 19.076, longitude: 72.878, durationS: 1542, distanceM: 4630, startedAt: new Date().toISOString(), joinCount: 3, distanceKm: 1.2, user: { id: 'demo-1', username: 'maya_runs', displayName: 'Maya Patel', photoUrl: null } },
  { id: 'demo-live-2', type: 'RIDE', visibility: 'FOLLOWERS', latitude: 19.08, longitude: 72.87, durationS: 3120, distanceM: 14100, startedAt: new Date().toISOString(), joinCount: 1, distanceKm: 3.8, user: { id: 'demo-2', username: 'arjun_moves', displayName: 'Arjun Mehta', photoUrl: null } },
];
export function LiveActivityPanel() { const [items, setItems] = useState<LiveActivity[]>(demo); const [notice, setNotice] = useState('Demo sessions are shown until you share your location.'); const [joining, setJoining] = useState(''); useEffect(() => { const load = () => { if (!navigator.geolocation) return; navigator.geolocation.getCurrentPosition(async position => { try { const response = await api<{live: LiveActivity[]}>(`/live/nearby?latitude=${position.coords.latitude}&longitude=${position.coords.longitude}`); setItems(response.live); setNotice(response.live.length ? 'Live sessions refresh every 20 seconds.' : 'No live sessions nearby right now.'); } catch { setNotice('Showing sample live sessions — connect your database to see real nearby activity.'); } }, () => undefined, { maximumAge: 300_000, timeout: 5_000 }); }; load(); const timer = setInterval(load, 20_000); return () => clearInterval(timer); }, []); async function join(item: LiveActivity) { if (item.id.startsWith('demo-')) { setNotice('Demo mode: joining is available once real live sharing is connected.'); return; } setJoining(item.id); try { await api(`/live/${item.id}/join`, { method: 'POST' }); setItems(current => current.map(value => value.id === item.id ? { ...value, joinCount: value.joinCount + 1 } : value)); } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not join live activity'); } finally { setJoining(''); } } return <section className="live-panel card stack"><div className="row"><div className="live-dot"/><div className="grow"><h2>Live near you</h2><p className="hint">{notice}</p></div><span className="live-label">LIVE</span></div>{items.map(item => <article className="live-card" key={item.id}><div className="avatar small">{item.user.displayName[0]}</div><div className="grow"><strong>{item.user.displayName}</strong><small>{labelFor(item.type)} · {formatDistance(item.distanceM)} · {formatDuration(item.durationS)}</small><small>Approx. {item.distanceKm.toFixed(1)} km away · {item.joinCount} connected</small></div><button className="button secondary" onClick={() => void join(item)} disabled={joining === item.id}>{joining === item.id ? 'Joining…' : 'Join'}</button></article>)}</section>; }
