'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { api, type SocialActivity, type User } from '../lib/api';
import { ActivityCard } from './activity-card';

function Avatar({ user }: { user: User }) { const photo = user.profile?.photoUrl; return photo ? <img className="avatar" src={photo} alt={`${user.profile?.displayName ?? user.username}'s profile photo`} /> : <div className="avatar" aria-hidden>{(user.profile?.displayName ?? user.username)[0]?.toUpperCase()}</div>; }
export function MyProfile() { const [user, setUser] = useState<User>(); const [activities, setActivities] = useState<SocialActivity[]>([]); const [error, setError] = useState(''); useEffect(() => { api<{user: User}>('/auth/me').then(async response => { setUser(response.user); return api<{activities: SocialActivity[]}>(`/users/${response.user.username}/activities`); }).then(response => setActivities(response.activities)).catch(() => setError('Please log in to view your profile.')); }, []); if (error) return <section className="card stack"><p>{error}</p><Link className="button" href="/login">Log in</Link></section>; if (!user) return <p className="hint">Loading profile…</p>; return <section className="stack"><div className="profile-head card"><Avatar user={user}/><div className="grow"><h1>{user.profile?.displayName}</h1><p className="hint">@{user.username}</p></div><Link className="button secondary" href="/profile/edit">Edit profile</Link></div><section className="card"><h2>About</h2><p>{user.profile?.bio || 'Add a bio to tell your movement community about you.'}</p></section><h2>Recent activities</h2>{activities.length ? activities.map(activity => <ActivityCard key={activity.id} initial={activity}/>) : <section className="card empty-state"><p>Activities you sync and share will appear here.</p></section>}<button className="button danger" onClick={async () => { await api('/auth/logout', { method: 'POST' }); location.href = '/login'; }}>Log out</button></section>; }
export function EditProfile() { const [user, setUser] = useState<User>(); const [message, setMessage] = useState(''); useEffect(() => { api<{user: User}>('/auth/me').then(response => setUser(response.user)).catch(() => location.href = '/login'); }, []); async function save(form: FormData) { setMessage(''); try { const data = Object.fromEntries(form); await api('/users/me/profile', { method: 'PATCH', body: JSON.stringify({ ...data, bio: data.bio || null, photoUrl: data.photoUrl || null, discoverable: data.discoverable === 'on' }) }); setMessage('Profile saved.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not save profile'); } } if (!user) return <p className="hint">Loading…</p>; const p = user.profile!; return <section className="card stack"><div><h1>Edit profile</h1><p className="hint">Nearby discovery stores only your approximate area, never a live exact location.</p></div><form className="stack" action={save}><label className="field">Display name<input name="displayName" required defaultValue={p.displayName}/></label><label className="field">Bio<textarea name="bio" maxLength={280} defaultValue={p.bio ?? ''}/></label><label className="field">Profile photo URL<input name="photoUrl" type="url" defaultValue={p.photoUrl ?? ''} placeholder="https://…"/></label><label className="field">Profile visibility<select name="profileVisibility" defaultValue={p.profileVisibility}><option value="PUBLIC">Public</option><option value="FOLLOWERS">Followers only</option><option value="PRIVATE">Private</option></select></label><label className="field">Route visibility<select name="routeVisibility" defaultValue={p.routeVisibility}><option value="PRIVATE">Only me</option><option value="FOLLOWERS">Followers only</option><option value="PUBLIC">Public</option></select></label><label className="row"><input name="discoverable" type="checkbox" defaultChecked={p.discoverable}/> Let people near me discover my approximate area</label>{message && <p role="status" className={message === 'Profile saved.' ? 'hint' : 'error'}>{message}</p>}<button className="button">Save changes</button></form></section>; }
